name: Build
on: [push, workflow_dispatch]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build
        run: |
          pip install buildozer cython==0.29.33
          yes | buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
